package main

import (
	"fmt"
	"io"
	"sort"
	"strings"
)

// writeYAML emits the Report as YAML. We write YAML by hand (rather than
// depending on gopkg.in/yaml.v3) so the tool has a zero-dependency build.
// The output is designed to be consumed by a future diagramming app, so we
// keep the shape predictable and well-commented.
func writeYAML(w io.Writer, r Report) error {
	bw := &buf{out: w}

	bw.line("# Spring Boot attack-surface map")
	bw.line("# Generated by spring-attack-surface scanner.")
	bw.line("# Target stack: Java 21, Spring Framework 6, Spring Boot 3.5.13")
	bw.line("# Shape: metadata + findings[]; each finding is a distinct attack entry point.")
	bw.line("")

	bw.line("metadata:")
	bw.kv(1, "scanned_path", r.ScannedPath)
	bw.kv(1, "scan_time", r.ScanTime)
	bw.kv(1, "java_version", r.JavaVersion)
	bw.kv(1, "spring_framework_version", r.SpringVersion)
	bw.kv(1, "spring_boot_version", r.BootVersion)
	bw.kvi(1, "files_scanned", r.FilesScanned)
	bw.kvi(1, "total_findings", r.TotalFindings)

	bw.line("  by_category:")
	for _, k := range sortedKeys(r.ByCategory) {
		bw.kvi(2, k, r.ByCategory[k])
	}
	bw.line("  by_severity:")
	for _, k := range sortedKeys(r.BySeverity) {
		bw.kvi(2, k, r.BySeverity[k])
	}

	bw.line("")
	bw.line("# Each attack_surface entry is a node for the downstream diagram tool.")
	bw.line("# - id:             stable within this report")
	bw.line("# - category:       high-level grouping (http_endpoint, file_io_disk, ...)")
	bw.line("# - entry_point:    canonical address (e.g. 'POST /api/users')")
	bw.line("# - package/class:  Java location")
	bw.line("# - method:         enclosing method name (empty for class-level surface)")
	bw.line("# - attack_vectors: OWASP-style tags for risk modeling")
	bw.line("attack_surface:")

	// Stable ordering: severity desc, then category, then file, then line.
	sorted := append([]Finding{}, r.Findings...)
	sort.SliceStable(sorted, func(i, j int) bool {
		if sevRank(sorted[i].Severity) != sevRank(sorted[j].Severity) {
			return sevRank(sorted[i].Severity) > sevRank(sorted[j].Severity)
		}
		if sorted[i].Category != sorted[j].Category {
			return sorted[i].Category < sorted[j].Category
		}
		if sorted[i].File != sorted[j].File {
			return sorted[i].File < sorted[j].File
		}
		return sorted[i].Line < sorted[j].Line
	})

	for _, f := range sorted {
		bw.line("  - id: " + fmt.Sprint(f.ID))
		bw.kv(2, "category", f.Category)
		bw.kv(2, "entry_point", f.EntryPoint)
		if f.HTTPMethod != "" {
			bw.kv(2, "http_method", f.HTTPMethod)
		}
		bw.kv(2, "package", f.Package)
		bw.kv(2, "class", f.Class)
		bw.kv(2, "method", f.Method)
		bw.kv(2, "file", f.File)
		bw.kvi(2, "line", f.Line)
		bw.kv(2, "severity", f.Severity)
		bw.kv(2, "description", f.Description)
		bw.kv(2, "snippet", f.Snippet)
		if len(f.AttackVectors) > 0 {
			bw.line("    attack_vectors:")
			for _, v := range f.AttackVectors {
				bw.line("      - " + yamlString(v))
			}
		} else {
			bw.line("    attack_vectors: []")
		}
	}

	return bw.err
}

// ---------------------------------------------------------------------------
// YAML writing helpers
// ---------------------------------------------------------------------------

type buf struct {
	out io.Writer
	err error
}

func (b *buf) line(s string) {
	if b.err != nil {
		return
	}
	_, b.err = fmt.Fprintln(b.out, s)
}

func (b *buf) kv(indent int, k, v string) {
	b.line(strings.Repeat("  ", indent) + k + ": " + yamlString(v))
}

func (b *buf) kvi(indent int, k string, v int) {
	b.line(strings.Repeat("  ", indent) + k + ": " + fmt.Sprint(v))
}

// yamlString quotes a value if necessary. We always quote with double quotes
// when the string contains any character that would complicate YAML parsing.
func yamlString(s string) string {
	if s == "" {
		return "\"\""
	}
	needsQuote := false
	for _, r := range s {
		if r == ':' || r == '#' || r == '\n' || r == '"' || r == '\\' ||
			r == '\'' || r == '{' || r == '}' || r == '[' || r == ']' ||
			r == ',' || r == '&' || r == '*' || r == '!' || r == '|' ||
			r == '>' || r == '%' || r == '@' || r == '`' || r == '?' {
			needsQuote = true
			break
		}
	}
	// Also quote if it starts with whitespace / dash / number-like, or is a
	// reserved word.
	switch strings.ToLower(s) {
	case "true", "false", "null", "yes", "no", "on", "off", "~":
		needsQuote = true
	}
	if !needsQuote {
		return s
	}
	esc := strings.ReplaceAll(s, "\\", "\\\\")
	esc = strings.ReplaceAll(esc, "\"", "\\\"")
	esc = strings.ReplaceAll(esc, "\n", "\\n")
	esc = strings.ReplaceAll(esc, "\t", "\\t")
	return "\"" + esc + "\""
}

func sortedKeys(m map[string]int) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

func sevRank(s string) int {
	switch s {
	case "critical":
		return 4
	case "high":
		return 3
	case "medium":
		return 2
	case "low":
		return 1
	}
	return 0
}
